const plants = [

  // --- Sun / Wet-Moist Perennials & Sedges ---
  {
    id: 1,
    scientificName: "Anemone canadensis",
    commonName: "Canada Anemone",
    heightMin: 1, heightMax: 3,
    light: ["sun", "part-sun", "shade", "part-shade"],
    moisture: ["dry", "moist"],
    type: "perennial", native: true, pollinatorValue: true,
    color: ["white"],
    difficulty: "easy",
    notes: "Highly adaptable — tolerates sun to shade and dry to moist soils. Can spread vigorously."
  },
  {
    id: 2,
    scientificName: "Asclepias incarnata",
    commonName: "Swamp Milkweed",
    heightMin: 2, heightMax: 4,
    light: ["sun", "part-sun"],
    moisture: ["wet", "moist"],
    type: "perennial", native: true, pollinatorValue: true,
    color: ["pink"],
    difficulty: "easy"
  },
  {
    id: 3,
    scientificName: "Boltonia asteroides",
    commonName: "False Aster",
    heightMin: 3, heightMax: 4,
    light: ["sun", "part-sun"],
    moisture: ["wet", "dry"],
    type: "perennial", native: true, pollinatorValue: true,
    color: ["white", "pink"],
    difficulty: "easy"
  },
  {
    id: 4,
    scientificName: "Carex spp.",
    commonName: "Sedges",
    heightMin: 1, heightMax: 3,
    light: ["sun"],
    moisture: ["wet", "moist"],
    type: "sedge", native: true, pollinatorValue: false,
    color: ["foliage"],
    difficulty: "easy"
  },
  {
    id: 5,
    scientificName: "Chelone glabra",
    commonName: "White Turtlehead",
    heightMin: 1, heightMax: 3,
    light: ["sun", "part-sun", "shade", "part-shade"],
    moisture: ["wet", "moist"],
    type: "perennial", native: true, pollinatorValue: true,
    color: ["white"],
    difficulty: "moderate"
  },
  {
    id: 6,
    scientificName: "Chelone lyonii",
    commonName: "Pink Turtlehead",
    heightMin: 2, heightMax: 3,
    light: ["sun", "part-sun"],
    moisture: ["wet", "moist"],
    type: "perennial", native: true, pollinatorValue: true,
    color: ["pink"],
    difficulty: "moderate"
  },
  {
    id: 7,
    scientificName: "Coreopsis rosea",
    commonName: "Pink Coreopsis",
    heightMin: 1, heightMax: 1,
    light: ["sun", "part-sun"],
    moisture: ["wet", "moist"],
    type: "perennial", native: true, pollinatorValue: true,
    color: ["pink"],
    difficulty: "easy"
  },
  {
    id: 8,
    scientificName: "Eupatorium fistulosum",
    commonName: "Joe-Pye Weed",
    heightMin: 3, heightMax: 8,
    light: ["sun", "part-sun"],
    moisture: ["wet", "moist"],
    type: "perennial", native: true, pollinatorValue: true,
    color: ["pink", "purple"],
    difficulty: "easy"
  },
  {
    id: 9,
    scientificName: "Filipendula rubra",
    commonName: "Queen-of-the-Prairie",
    heightMin: 3, heightMax: 7,
    light: ["sun", "part-sun"],
    moisture: ["wet", "moist"],
    type: "perennial", native: true, pollinatorValue: true,
    color: ["pink"],
    difficulty: "moderate"
  },
  {
    id: 10,
    scientificName: "Geranium maculatum",
    commonName: "Wild Geranium",
    heightMin: 1, heightMax: 2,
    light: ["sun", "part-sun"],
    moisture: ["moist"],
    type: "perennial", native: true, pollinatorValue: true,
    color: ["pink", "lavender"],
    difficulty: "easy"
  },
  {
    id: 11,
    scientificName: "Helenium autumnale",
    commonName: "Helen's Flower",
    heightMin: 2, heightMax: 6,
    light: ["sun", "shade"],
    moisture: ["moist"],
    type: "perennial", native: true, pollinatorValue: true,
    color: ["yellow", "orange"],
    difficulty: "easy"
  },
  {
    id: 12,
    scientificName: "Iris versicolor",
    commonName: "Blue Flag Iris",
    heightMin: 3, heightMax: 4,
    light: ["sun", "part-sun"],
    moisture: ["wet", "moist"],
    type: "perennial", native: true, pollinatorValue: true,
    color: ["blue", "violet"],
    difficulty: "moderate"
  },
  {
    id: 13,
    scientificName: "Liatris spicata",
    commonName: "Blazing Star",
    heightMin: 2, heightMax: 5,
    light: ["sun", "part-sun"],
    moisture: ["wet", "moist"],
    type: "perennial", native: true, pollinatorValue: true,
    color: ["purple", "pink"],
    difficulty: "easy"
  },
  {
    id: 14,
    scientificName: "Liatris squarrosa",
    commonName: "Gayfeather",
    heightMin: 1, heightMax: 3,
    light: ["sun", "part-sun"],
    moisture: ["moist"],
    type: "perennial", native: true, pollinatorValue: true,
    color: ["purple"],
    difficulty: "easy"
  },
  {
    id: 15,
    scientificName: "Lilium canadense",
    commonName: "Canada Lily",
    heightMin: 2, heightMax: 6,
    light: ["sun", "part-sun"],
    moisture: ["wet", "moist"],
    type: "perennial", native: true, pollinatorValue: true,
    color: ["yellow", "orange"],
    difficulty: "moderate"
  },
  {
    id: 16,
    scientificName: "Lobelia cardinalis",
    commonName: "Cardinal Flower",
    heightMin: 2, heightMax: 4,
    light: ["sun", "part-sun"],
    moisture: ["wet", "moist"],
    type: "perennial", native: true, pollinatorValue: true,
    color: ["red"],
    difficulty: "challenging",
    notes: "Can be difficult to establish and is short-lived, but reseeds well. Worth the effort for hummingbirds."
  },
  {
    id: 17,
    scientificName: "Lobelia siphilitica",
    commonName: "Great Blue Lobelia",
    heightMin: 1, heightMax: 4,
    light: ["sun", "shade"],
    moisture: ["wet", "moist"],
    type: "perennial", native: true, pollinatorValue: true,
    color: ["blue"],
    difficulty: "moderate"
  },
  {
    id: 18,
    scientificName: "Mimulus ringens",
    commonName: "Allegheny Monkey Flower",
    heightMin: 1, heightMax: 3,
    light: ["sun", "part-sun", "part-shade"],
    moisture: ["wet", "moist"],
    type: "perennial", native: true, pollinatorValue: true,
    color: ["lavender", "purple"],
    difficulty: "moderate"
  },
  {
    id: 19,
    scientificName: "Monarda didyma",
    commonName: "Bee Balm",
    heightMin: 2, heightMax: 5,
    light: ["sun", "part-sun"],
    moisture: ["wet", "moist"],
    type: "perennial", native: true, pollinatorValue: true,
    color: ["red"],
    difficulty: "easy"
  },
  {
    id: 20,
    scientificName: "Phlox paniculata",
    commonName: "Summer Phlox",
    heightMin: 2, heightMax: 5,
    light: ["sun", "part-sun"],
    moisture: ["moist"],
    type: "perennial", native: true, pollinatorValue: true,
    color: ["pink", "white", "purple"],
    difficulty: "easy"
  },
  {
    id: 21,
    scientificName: "Sisyrinchium angustifolium",
    commonName: "Blue-eyed Grass",
    heightMin: 1, heightMax: 2,
    light: ["sun", "part-sun"],
    moisture: ["moist"],
    type: "perennial", native: true, pollinatorValue: true,
    color: ["blue", "violet"],
    difficulty: "easy"
  },
  {
    id: 22,
    scientificName: "Stokesia laevis",
    commonName: "Stokes' Aster",
    heightMin: 1, heightMax: 2,
    light: ["sun", "part-sun"],
    moisture: ["moist"],
    type: "perennial", native: true, pollinatorValue: true,
    color: ["blue", "lavender"],
    difficulty: "easy"
  },
  {
    id: 23,
    scientificName: "Symphyotrichum novae-angliae",
    commonName: "New England Aster",
    heightMin: 2, heightMax: 6,
    light: ["sun", "part-sun"],
    moisture: ["moist"],
    type: "perennial", native: true, pollinatorValue: true,
    color: ["purple", "pink"],
    difficulty: "easy"
  },
  {
    id: 24,
    scientificName: "Symphyotrichum novi-belgii",
    commonName: "New York Aster",
    heightMin: 1, heightMax: 4,
    light: ["sun", "part-sun"],
    moisture: ["moist"],
    type: "perennial", native: true, pollinatorValue: true,
    color: ["blue", "purple"],
    difficulty: "easy"
  },
  {
    id: 25,
    scientificName: "Vernonia noveboracensis",
    commonName: "New York Ironweed",
    heightMin: 3, heightMax: 8,
    light: ["sun", "part-sun"],
    moisture: ["wet", "moist"],
    type: "perennial", native: true, pollinatorValue: true,
    color: ["purple"],
    difficulty: "easy"
  },
  {
    id: 26,
    scientificName: "Veronicastrum virginicum",
    commonName: "Culver's Root",
    heightMin: 3, heightMax: 6,
    light: ["sun", "part-sun"],
    moisture: ["wet", "moist"],
    type: "perennial", native: true, pollinatorValue: true,
    color: ["white"],
    difficulty: "easy"
  },
  {
    id: 27,
    scientificName: "Zizia aurea",
    commonName: "Golden Alexanders",
    heightMin: 1, heightMax: 3,
    light: ["sun", "part-sun", "part-shade", "shade"],
    moisture: ["wet", "dry", "moist"],
    type: "perennial", native: true, pollinatorValue: true,
    color: ["yellow"],
    difficulty: "easy"
  },

  // --- Shade / Mixed Moisture Perennials ---
  {
    id: 58,
    scientificName: "Aquilegia canadensis",
    commonName: "Wild Columbine",
    heightMin: 1, heightMax: 3,
    light: ["part-shade"],
    moisture: ["dry", "moist"],
    type: "perennial", native: true, pollinatorValue: true,
    color: ["red", "yellow"],
    difficulty: "easy",
    notes: "Hummingbird magnet in spring. Self-seeds freely and naturalizes well under trees."
  },
  {
    id: 59,
    scientificName: "Chrysogonum virginianum",
    commonName: "Green-and-Gold",
    heightMin: 0.5, heightMax: 1,
    light: ["shade", "part-shade"],
    moisture: ["dry", "moist"],
    type: "perennial", native: true, pollinatorValue: true,
    color: ["yellow"],
    difficulty: "easy",
    notes: "Excellent low ground cover, 6–12 inches. Long blooming season from spring into summer."
  },
  {
    id: 60,
    scientificName: "Eurybia divaricata",
    commonName: "White Wood Aster",
    heightMin: 1, heightMax: 3,
    light: ["shade", "part-shade"],
    moisture: ["dry", "moist"],
    type: "perennial", native: true, pollinatorValue: true,
    color: ["white"],
    difficulty: "easy"
  },
  {
    id: 61,
    scientificName: "Helianthus divaricatus",
    commonName: "Woodland Sunflower",
    heightMin: 1.5, heightMax: 6,
    light: ["part-shade"],
    moisture: ["dry", "moist"],
    type: "perennial", native: true, pollinatorValue: true,
    color: ["yellow"],
    difficulty: "easy"
  },
  {
    id: 62,
    scientificName: "Heuchera americana",
    commonName: "Alumroot",
    heightMin: 1, heightMax: 2,
    light: ["sun", "shade"],
    moisture: ["dry", "moist"],
    type: "perennial", native: true, pollinatorValue: true,
    color: ["white", "pink"],
    difficulty: "easy"
  },
  {
    id: 63,
    scientificName: "Smilacina racemosa",
    commonName: "False Solomon's Seal",
    heightMin: 1, heightMax: 3,
    light: ["shade", "part-shade"],
    moisture: ["dry", "moist"],
    type: "perennial", native: true, pollinatorValue: true,
    color: ["white"],
    difficulty: "easy"
  },
  {
    id: 64,
    scientificName: "Solidago caesia",
    commonName: "Wreath Goldenrod",
    heightMin: 1, heightMax: 4,
    light: ["sun", "shade"],
    moisture: ["dry", "moist"],
    type: "perennial", native: true, pollinatorValue: true,
    color: ["yellow"],
    difficulty: "easy",
    notes: "One of the few goldenrods that thrives in shade — a valuable late-season nectar source."
  },
  {
    id: 65,
    scientificName: "Symphyotrichum cordifolium",
    commonName: "Blue Wood Aster",
    heightMin: 2, heightMax: 3,
    light: ["shade", "part-shade"],
    moisture: ["dry", "moist"],
    type: "perennial", native: true, pollinatorValue: true,
    color: ["blue", "lavender"],
    difficulty: "easy"
  },
  {
    id: 66,
    scientificName: "Waldsteinia fragaroides",
    commonName: "Barren Strawberry",
    heightMin: 0.25, heightMax: 0.5,
    light: ["shade", "part-shade"],
    moisture: ["dry", "moist"],
    type: "perennial", native: true, pollinatorValue: true,
    color: ["yellow"],
    difficulty: "easy",
    notes: "Dense, spreading ground cover at 3–6 inches. Ideal under trees where little else will grow."
  },

  // --- Sun / Dry-Moist Perennials ---
  {
    id: 28,
    scientificName: "Agastache foeniculum",
    commonName: "Anise Hyssop",
    heightMin: 3, heightMax: 5,
    light: ["sun", "part-sun"],
    moisture: ["dry", "moist"],
    type: "perennial", native: true, pollinatorValue: true,
    color: ["blue", "purple"],
    difficulty: "easy"
  },
  {
    id: 29,
    scientificName: "Allium cernuum",
    commonName: "Nodding Onion",
    heightMin: 1, heightMax: 2,
    light: ["sun", "part-sun"],
    moisture: ["dry", "moist"],
    type: "perennial", native: true, pollinatorValue: true,
    color: ["pink", "white"],
    difficulty: "easy"
  },
  {
    id: 30,
    scientificName: "Amsonia tabernaemontana",
    commonName: "Blue Star",
    heightMin: 2, heightMax: 4,
    light: ["sun", "part-sun"],
    moisture: ["dry", "moist"],
    type: "perennial", native: true, pollinatorValue: true,
    color: ["blue"],
    difficulty: "easy"
  },
  {
    id: 31,
    scientificName: "Asclepias tuberosa",
    commonName: "Butterfly Weed",
    heightMin: 1, heightMax: 3,
    light: ["sun", "part-sun"],
    moisture: ["dry"],
    type: "perennial", native: true, pollinatorValue: true,
    color: ["orange"],
    difficulty: "moderate",
    notes: "One of the best milkweeds for monarchs. Needs excellent drainage — do not overwater."
  },
  {
    id: 32,
    scientificName: "Baptisia australis",
    commonName: "False Blue Indigo",
    heightMin: 3, heightMax: 5,
    light: ["sun", "part-sun"],
    moisture: ["dry", "moist"],
    type: "perennial", native: true, pollinatorValue: true,
    color: ["blue", "purple"],
    difficulty: "moderate",
    notes: "Slow to establish but extremely long-lived once settled. Do not move after planting."
  },
  {
    id: 33,
    scientificName: "Chrysopsis mariana",
    commonName: "Golden Aster",
    heightMin: 1, heightMax: 2,
    light: ["sun", "part-sun"],
    moisture: ["dry"],
    type: "perennial", native: true, pollinatorValue: true,
    color: ["yellow"],
    difficulty: "easy"
  },
  {
    id: 34,
    scientificName: "Coreopsis verticillata",
    commonName: "Threadleaf Coreopsis",
    heightMin: 1, heightMax: 3,
    light: ["sun", "part-sun"],
    moisture: ["dry", "moist"],
    type: "perennial", native: true, pollinatorValue: true,
    color: ["yellow"],
    difficulty: "easy"
  },
  {
    id: 35,
    scientificName: "Eryngium yuccifolium",
    commonName: "Rattlesnake Master",
    heightMin: 2, heightMax: 3,
    light: ["sun"],
    moisture: ["dry", "moist"],
    type: "perennial", native: true, pollinatorValue: true,
    color: ["white", "silver"],
    difficulty: "moderate"
  },
  {
    id: 36,
    scientificName: "Eupatorium hyssopifolium",
    commonName: "Thoroughwort",
    heightMin: 1, heightMax: 4,
    light: ["sun", "part-sun"],
    moisture: ["dry", "moist"],
    type: "perennial", native: true, pollinatorValue: true,
    color: ["white"],
    difficulty: "easy"
  },
  {
    id: 37,
    scientificName: "Heliopsis helianthoides",
    commonName: "Oxeye",
    heightMin: 1, heightMax: 5,
    light: ["sun", "part-sun"],
    moisture: ["dry", "moist"],
    type: "perennial", native: true, pollinatorValue: true,
    color: ["yellow"],
    difficulty: "easy"
  },
  {
    id: 38,
    scientificName: "Liatris scariosa",
    commonName: "Blazing Star",
    heightMin: 1, heightMax: 4,
    light: ["sun", "part-sun"],
    moisture: ["dry", "moist"],
    type: "perennial", native: true, pollinatorValue: true,
    color: ["purple"],
    difficulty: "easy"
  },
  {
    id: 39,
    scientificName: "Monarda fistulosa",
    commonName: "Wild Bee Balm",
    heightMin: 2, heightMax: 5,
    light: ["sun", "part-sun"],
    moisture: ["dry", "moist"],
    type: "perennial", native: true, pollinatorValue: true,
    color: ["lavender", "pink"],
    difficulty: "easy"
  },
  {
    id: 40,
    scientificName: "Oenothera fruticosa",
    commonName: "Sundrops",
    heightMin: 1, heightMax: 3,
    light: ["sun", "part-sun"],
    moisture: ["dry", "moist"],
    type: "perennial", native: true, pollinatorValue: true,
    color: ["yellow"],
    difficulty: "easy"
  },
  {
    id: 41,
    scientificName: "Opuntia humifusa",
    commonName: "Pricklypear Cactus",
    heightMin: 0.5, heightMax: 1,
    light: ["sun"],
    moisture: ["dry"],
    type: "perennial", native: true, pollinatorValue: true,
    color: ["yellow"],
    difficulty: "moderate",
    notes: "Native eastern cactus — surprisingly hardy. Striking blooms attract specialist bees. Handle with care."
  },
  {
    id: 42,
    scientificName: "Penstemon digitalis",
    commonName: "Beardtongue",
    heightMin: 2, heightMax: 5,
    light: ["sun", "part-sun"],
    moisture: ["dry", "moist"],
    type: "perennial", native: true, pollinatorValue: true,
    color: ["white", "pink"],
    difficulty: "easy"
  },
  {
    id: 43,
    scientificName: "Penstemon smallii",
    commonName: "Small's Beardtongue",
    heightMin: 1, heightMax: 3,
    light: ["part-sun"],
    moisture: ["dry", "moist"],
    type: "perennial", native: true, pollinatorValue: true,
    color: ["pink", "purple"],
    difficulty: "moderate"
  },
  {
    id: 44,
    scientificName: "Phlox subulata",
    commonName: "Moss Phlox",
    heightMin: 0.2, heightMax: 0.5,
    light: ["sun"],
    moisture: ["dry"],
    type: "perennial", native: true, pollinatorValue: true,
    color: ["pink", "white", "purple"],
    difficulty: "easy",
    notes: "Ground-hugging mat, only 2–6 inches tall. Spectacular spring bloom, low maintenance after."
  },
  {
    id: 45,
    scientificName: "Physostegia virginiana",
    commonName: "Obedient Plant",
    heightMin: 2, heightMax: 5,
    light: ["sun", "part-sun"],
    moisture: ["dry", "moist"],
    type: "perennial", native: true, pollinatorValue: true,
    color: ["pink", "lavender"],
    difficulty: "easy",
    notes: "Can spread aggressively in moist, fertile soil. Plant where it has room to roam."
  },
  {
    id: 46,
    scientificName: "Rudbeckia fulgida",
    commonName: "Brown-eyed Susan",
    heightMin: 1, heightMax: 4,
    light: ["sun", "part-sun"],
    moisture: ["dry", "moist"],
    type: "perennial", native: true, pollinatorValue: true,
    color: ["yellow", "orange"],
    difficulty: "easy"
  },
  {
    id: 47,
    scientificName: "Rudbeckia hirta",
    commonName: "Black-eyed Susan",
    heightMin: 1, heightMax: 3,
    light: ["sun", "part-sun"],
    moisture: ["dry", "moist"],
    type: "perennial", native: true, pollinatorValue: true,
    color: ["yellow"],
    difficulty: "easy"
  },
  {
    id: 48,
    scientificName: "Silphium perfoliatum",
    commonName: "Cup Plant",
    heightMin: 3, heightMax: 8,
    light: ["sun", "part-sun"],
    moisture: ["dry", "moist"],
    type: "perennial", native: true, pollinatorValue: true,
    color: ["yellow"],
    difficulty: "easy",
    notes: "Leaf cups collect rainwater — a water source for birds and insects. Very tall; plant at the back."
  },
  {
    id: 49,
    scientificName: "Solidago speciosa",
    commonName: "Showy Goldenrod",
    heightMin: 2, heightMax: 6,
    light: ["sun", "part-sun"],
    moisture: ["dry", "moist"],
    type: "perennial", native: true, pollinatorValue: true,
    color: ["yellow"],
    difficulty: "easy"
  },
  {
    id: 50,
    scientificName: "Symphyotrichum laeve",
    commonName: "Smooth Aster",
    heightMin: 2, heightMax: 4,
    light: ["sun"],
    moisture: ["dry", "moist"],
    type: "perennial", native: true, pollinatorValue: true,
    color: ["blue", "lavender"],
    difficulty: "easy"
  },
  {
    id: 51,
    scientificName: "Symphyotrichum oblongifolium",
    commonName: "Aromatic Aster",
    heightMin: 1, heightMax: 3,
    light: ["sun"],
    moisture: ["dry", "moist"],
    type: "perennial", native: true, pollinatorValue: true,
    color: ["purple"],
    difficulty: "easy"
  },
  {
    id: 52,
    scientificName: "Vernonia glauca",
    commonName: "Tawny Ironweed",
    heightMin: 3, heightMax: 5,
    light: ["sun"],
    moisture: ["dry", "moist"],
    type: "perennial", native: true, pollinatorValue: true,
    color: ["purple"],
    difficulty: "easy"
  },

  // --- Native Grasses ---
  {
    id: 53,
    scientificName: "Andropogon gerardii",
    commonName: "Big Bluestem",
    heightMin: 2, heightMax: 6,
    light: ["sun", "part-sun"],
    moisture: ["dry", "moist"],
    type: "grass", native: true, pollinatorValue: false,
    color: ["foliage"],
    difficulty: "easy"
  },
  {
    id: 54,
    scientificName: "Panicum virgatum",
    commonName: "Switch Grass",
    heightMin: 3, heightMax: 6,
    light: ["sun", "part-sun"],
    moisture: ["dry", "wet"],
    type: "grass", native: true, pollinatorValue: false,
    color: ["foliage"],
    difficulty: "easy"
  },
  {
    id: 55,
    scientificName: "Schizachyrium scoparium",
    commonName: "Little Bluestem",
    heightMin: 1, heightMax: 4,
    light: ["sun"],
    moisture: ["dry"],
    type: "grass", native: true, pollinatorValue: false,
    color: ["foliage"],
    difficulty: "easy"
  },
  {
    id: 56,
    scientificName: "Sorghastrum nutans",
    commonName: "Indian Grass",
    heightMin: 3, heightMax: 6,
    light: ["sun"],
    moisture: ["dry", "moist"],
    type: "grass", native: true, pollinatorValue: false,
    color: ["foliage"],
    difficulty: "easy"
  },
  {
    id: 57,
    scientificName: "Sporobolus heterolepis",
    commonName: "Prairie Dropseed",
    heightMin: 2, heightMax: 3,
    light: ["sun"],
    moisture: ["dry"],
    type: "grass", native: true, pollinatorValue: false,
    color: ["foliage"],
    difficulty: "easy"
  },

  // --- Shade Perennials & Ferns ---
  {
    id: 67,
    scientificName: "Actaea pachypoda",
    commonName: "Doll's Eyes",
    heightMin: 1, heightMax: 3,
    light: ["shade", "part-shade"],
    moisture: ["moist"],
    type: "perennial", native: true, pollinatorValue: false,
    color: ["white"],
    difficulty: "moderate",
    notes: "Striking white berries with dark dots are toxic — beautiful but not for gardens with young children."
  },
  {
    id: 68,
    scientificName: "Adiantum pedatum",
    commonName: "Maidenhair Fern",
    heightMin: 1, heightMax: 2,
    light: ["shade", "part-shade"],
    moisture: ["moist"],
    type: "fern", native: true, pollinatorValue: false,
    color: ["foliage"],
    difficulty: "moderate",
    notes: "One of the most elegant native ferns. Delicate fan-shaped fronds on wiry black stems."
  },
  {
    id: 69,
    scientificName: "Arisaema triphyllum",
    commonName: "Jack-in-the-Pulpit",
    heightMin: 1, heightMax: 3,
    light: ["shade", "part-shade"],
    moisture: ["wet", "moist"],
    type: "perennial", native: true, pollinatorValue: false,
    color: ["green", "purple"],
    difficulty: "moderate",
    notes: "Fascinating woodland plant. Produces bright red berries in fall. All parts are toxic if eaten raw."
  },
  {
    id: 70,
    scientificName: "Aruncus dioicus",
    commonName: "Goat's Beard",
    heightMin: 3, heightMax: 6,
    light: ["shade", "part-shade"],
    moisture: ["wet", "moist"],
    type: "perennial", native: true, pollinatorValue: true,
    color: ["white"],
    difficulty: "easy",
    notes: "Native to both eastern forests and Pacific Northwest woodlands. Impressive white plumes in summer."
  },
  {
    id: 71,
    scientificName: "Asarum canadense",
    commonName: "Wild Ginger",
    heightMin: 0.5, heightMax: 1,
    light: ["shade", "part-shade"],
    moisture: ["moist"],
    type: "perennial", native: true, pollinatorValue: false,
    color: ["foliage"],
    difficulty: "easy",
    notes: "Excellent dense ground cover for deep shade. Spreads slowly but reliably."
  },
  {
    id: 72,
    scientificName: "Athyrium filix-femina",
    commonName: "Lady Fern",
    heightMin: 1, heightMax: 3,
    light: ["part-shade"],
    moisture: ["wet", "moist"],
    type: "fern", native: true, pollinatorValue: false,
    color: ["foliage"],
    difficulty: "easy"
  },
  {
    id: 73,
    scientificName: "Caltha palustris",
    commonName: "Marsh Marigold",
    heightMin: 1, heightMax: 2,
    light: ["sun", "shade"],
    moisture: ["wet"],
    type: "perennial", native: true, pollinatorValue: true,
    color: ["yellow"],
    difficulty: "easy",
    notes: "One of the first spring bloomers. Needs consistently wet or boggy conditions."
  },
  {
    id: 74,
    scientificName: "Claytonia virginica",
    commonName: "Spring Beauty",
    heightMin: 0.5, heightMax: 1,
    light: ["shade"],
    moisture: ["moist"],
    type: "perennial", native: true, pollinatorValue: true,
    color: ["white", "pink"],
    difficulty: "easy",
    notes: "Ephemeral — dies back by summer. Naturalizes beautifully in lawns and under trees."
  },
  {
    id: 75,
    scientificName: "Actaea racemosa",
    commonName: "Black Cohosh",
    heightMin: 2, heightMax: 8,
    light: ["shade", "part-shade"],
    moisture: ["moist"],
    type: "perennial", native: true, pollinatorValue: true,
    color: ["white"],
    difficulty: "moderate",
    notes: "Tall dramatic spires of white flowers in summer. Slow to establish but striking."
  },
  {
    id: 76,
    scientificName: "Dicentra eximia",
    commonName: "Bleeding Heart",
    heightMin: 1, heightMax: 2,
    light: ["shade", "part-shade"],
    moisture: ["moist"],
    type: "perennial", native: true, pollinatorValue: true,
    color: ["pink"],
    difficulty: "easy",
    notes: "Native bleeding heart blooms spring through frost, unlike its Asian cousin. Long-season performer."
  },
  {
    id: 77,
    scientificName: "Erythronium americanum",
    commonName: "Trout Lily",
    heightMin: 0.5, heightMax: 1,
    light: ["shade", "part-shade"],
    moisture: ["moist"],
    type: "perennial", native: true, pollinatorValue: true,
    color: ["yellow"],
    difficulty: "challenging",
    notes: "Spring ephemeral with beautifully mottled leaves. Slow to establish — do not disturb once planted."
  },
  {
    id: 78,
    scientificName: "Eurybia macrophylla",
    commonName: "Big Leaf Aster",
    heightMin: 1, heightMax: 3,
    light: ["shade", "part-shade"],
    moisture: ["moist"],
    type: "perennial", native: true, pollinatorValue: true,
    color: ["lavender", "blue"],
    difficulty: "easy"
  },
  {
    id: 79,
    scientificName: "Hydrastis canadensis",
    commonName: "Goldenseal",
    heightMin: 0.5, heightMax: 1,
    light: ["shade", "part-shade"],
    moisture: ["moist"],
    type: "perennial", native: true, pollinatorValue: false,
    color: ["white"],
    difficulty: "challenging",
    notes: "At-risk native plant — avoid purchasing wild-collected plants. Buy only nursery propagated."
  },
  {
    id: 80,
    scientificName: "Iris cristata",
    commonName: "Dwarf Crested Iris",
    heightMin: 0.33, heightMax: 0.67,
    light: ["shade", "part-shade"],
    moisture: ["moist"],
    type: "perennial", native: true, pollinatorValue: true,
    color: ["blue", "lavender"],
    difficulty: "easy",
    notes: "Only 4–8 inches tall with lavender blooms. Perfect edging or ground cover for shade."
  },
  {
    id: 81,
    scientificName: "Jeffersonia diphylla",
    commonName: "Twinleaf",
    heightMin: 0.5, heightMax: 1,
    light: ["shade", "part-shade"],
    moisture: ["moist"],
    type: "perennial", native: true, pollinatorValue: true,
    color: ["white"],
    difficulty: "moderate"
  },
  {
    id: 82,
    scientificName: "Matteuccia struthiopteris",
    commonName: "Ostrich Fern",
    heightMin: 3, heightMax: 5,
    light: ["shade", "part-shade"],
    moisture: ["wet", "moist"],
    type: "fern", native: true, pollinatorValue: false,
    color: ["foliage"],
    difficulty: "easy",
    notes: "Dramatic vase-shaped fern. Spreads by runners — give it space. Fiddleheads are edible."
  },
  {
    id: 83,
    scientificName: "Mertensia virginica",
    commonName: "Virginia Bluebells",
    heightMin: 1, heightMax: 2,
    light: ["shade", "part-shade"],
    moisture: ["moist"],
    type: "perennial", native: true, pollinatorValue: true,
    color: ["blue"],
    difficulty: "moderate",
    notes: "Spring ephemeral with sky-blue trumpet flowers. Goes dormant by summer — plant with hostas to fill the gap."
  },
  {
    id: 84,
    scientificName: "Onoclea sensibilis",
    commonName: "Sensitive Fern",
    heightMin: 1, heightMax: 3,
    light: ["sun", "shade"],
    moisture: ["wet", "moist"],
    type: "fern", native: true, pollinatorValue: false,
    color: ["foliage"],
    difficulty: "easy",
    notes: "Dies back at first frost (hence 'sensitive'). Spreads readily — excellent for erosion control."
  },
  {
    id: 85,
    scientificName: "Osmunda cinnamomea",
    commonName: "Cinnamon Fern",
    heightMin: 2, heightMax: 5,
    light: ["sun", "shade"],
    moisture: ["wet", "moist"],
    type: "fern", native: true, pollinatorValue: false,
    color: ["foliage"],
    difficulty: "easy"
  },
  {
    id: 86,
    scientificName: "Osmunda regalis",
    commonName: "Royal Fern",
    heightMin: 2, heightMax: 4,
    light: ["shade", "part-shade"],
    moisture: ["wet", "moist"],
    type: "fern", native: true, pollinatorValue: false,
    color: ["foliage"],
    difficulty: "easy"
  },
  {
    id: 87,
    scientificName: "Pachysandra procumbens",
    commonName: "Allegheny Pachysandra",
    heightMin: 0.5, heightMax: 1,
    light: ["shade", "part-shade"],
    moisture: ["moist"],
    type: "perennial", native: true, pollinatorValue: false,
    color: ["white"],
    difficulty: "easy",
    notes: "The native alternative to invasive Japanese pachysandra. Semi-evergreen ground cover."
  },
  {
    id: 88,
    scientificName: "Packera aurea",
    commonName: "Golden Ragwort",
    heightMin: 1, heightMax: 2,
    light: ["shade", "part-shade"],
    moisture: ["wet", "moist"],
    type: "perennial", native: true, pollinatorValue: true,
    color: ["yellow"],
    difficulty: "easy"
  },
  {
    id: 89,
    scientificName: "Phlox divaricata",
    commonName: "Wild Blue Phlox",
    heightMin: 0.67, heightMax: 1.5,
    light: ["shade", "part-shade"],
    moisture: ["moist"],
    type: "perennial", native: true, pollinatorValue: true,
    color: ["blue", "lavender"],
    difficulty: "easy"
  },
  {
    id: 90,
    scientificName: "Phlox stolonifera",
    commonName: "Creeping Phlox",
    heightMin: 0.5, heightMax: 1,
    light: ["shade", "part-shade"],
    moisture: ["moist"],
    type: "perennial", native: true, pollinatorValue: true,
    color: ["pink", "purple"],
    difficulty: "easy"
  },
  {
    id: 91,
    scientificName: "Polemonium reptans",
    commonName: "Jacob's Ladder",
    heightMin: 1, heightMax: 2,
    light: ["shade", "part-shade"],
    moisture: ["moist"],
    type: "perennial", native: true, pollinatorValue: true,
    color: ["blue", "lavender"],
    difficulty: "easy"
  },
  {
    id: 92,
    scientificName: "Polygonatum biflorum",
    commonName: "Solomon's Seal",
    heightMin: 1, heightMax: 4,
    light: ["shade", "part-shade"],
    moisture: ["moist"],
    type: "perennial", native: true, pollinatorValue: true,
    color: ["white"],
    difficulty: "easy"
  },
  {
    id: 93,
    scientificName: "Polystichum acrostichoides",
    commonName: "Christmas Fern",
    heightMin: 1, heightMax: 2,
    light: ["shade", "part-shade"],
    moisture: ["moist"],
    type: "fern", native: true, pollinatorValue: false,
    color: ["foliage"],
    difficulty: "easy",
    notes: "Evergreen native fern — provides winter structure and cover. One of the most reliable shade plants."
  },
  {
    id: 94,
    scientificName: "Sanguinaria canadensis",
    commonName: "Bloodroot",
    heightMin: 0.5, heightMax: 1,
    light: ["shade", "part-shade"],
    moisture: ["moist"],
    type: "perennial", native: true, pollinatorValue: true,
    color: ["white"],
    difficulty: "moderate",
    notes: "Brilliant white spring ephemeral. Short-lived blooms but unforgettable. Goes dormant by midsummer."
  },
  {
    id: 95,
    scientificName: "Solidago flexicaulis",
    commonName: "Zigzag Goldenrod",
    heightMin: 1, heightMax: 3,
    light: ["shade", "part-shade"],
    moisture: ["moist"],
    type: "perennial", native: true, pollinatorValue: true,
    color: ["yellow"],
    difficulty: "easy",
    notes: "One of the few goldenrods for shade. Named for its distinctively zigzagging stem."
  },
  {
    id: 96,
    scientificName: "Spigelia marilandica",
    commonName: "Indian Pink",
    heightMin: 1, heightMax: 2,
    light: ["part-shade"],
    moisture: ["moist"],
    type: "perennial", native: true, pollinatorValue: true,
    color: ["red", "yellow"],
    difficulty: "moderate",
    notes: "Red tubular flowers with yellow star-shaped openings — extraordinary hummingbird plant."
  },
  {
    id: 97,
    scientificName: "Stylophorum diphyllum",
    commonName: "Celandine Poppy",
    heightMin: 1, heightMax: 2,
    light: ["shade", "part-shade"],
    moisture: ["moist"],
    type: "perennial", native: true, pollinatorValue: true,
    color: ["yellow"],
    difficulty: "easy",
    notes: "Cheerful yellow poppy-like blooms in spring shade. Self-seeds generously."
  },
  {
    id: 98,
    scientificName: "Tiarella cordifolia",
    commonName: "Foam Flower",
    heightMin: 0.5, heightMax: 1,
    light: ["sun", "shade"],
    moisture: ["moist"],
    type: "perennial", native: true, pollinatorValue: true,
    color: ["white", "pink"],
    difficulty: "easy"
  },
  {
    id: 99,
    scientificName: "Tradescantia virginiana",
    commonName: "Spiderwort",
    heightMin: 1, heightMax: 3,
    light: ["sun", "part-shade"],
    moisture: ["moist"],
    type: "perennial", native: true, pollinatorValue: true,
    color: ["blue", "purple"],
    difficulty: "easy"
  },
  {
    id: 100,
    scientificName: "Trillium grandiflorum",
    commonName: "Showy Trillium",
    heightMin: 1, heightMax: 2,
    light: ["shade", "part-shade"],
    moisture: ["moist"],
    type: "perennial", native: true, pollinatorValue: false,
    color: ["white"],
    difficulty: "challenging",
    notes: "Icon of the woodland garden. Slow growing — buy nursery propagated only, never wild-collected."
  },
  {
    id: 101,
    scientificName: "Uvularia grandiflora",
    commonName: "Merrybells",
    heightMin: 1, heightMax: 3,
    light: ["shade"],
    moisture: ["moist"],
    type: "perennial", native: true, pollinatorValue: true,
    color: ["yellow"],
    difficulty: "moderate"
  },
  {
    id: 102,
    scientificName: "Viola sp.",
    commonName: "Violets",
    heightMin: 0.1, heightMax: 1,
    light: ["sun", "shade"],
    moisture: ["moist"],
    type: "perennial", native: true, pollinatorValue: true,
    color: ["purple", "white"],
    difficulty: "easy",
    region: "east",
    notes: "Host plant for fritillary butterflies. Let them naturalize freely — they are doing important work."
  },

  // --- West Coast: Northwest Sunny Border — Perennials & Bulbs ---
  {
    id: 103,
    scientificName: "Heuchera micrantha",
    commonName: "Small-flowered Alumroot",
    heightMin: 1, heightMax: 2,
    light: ["shade", "part-shade"],
    moisture: ["dry", "moist"],
    type: "perennial", native: true, pollinatorValue: true,
    color: ["white", "pink"],
    difficulty: "easy",
    region: "west"
  },
  {
    id: 104,
    scientificName: "Symphyotrichum subspicatum",
    commonName: "Douglas' Aster",
    heightMin: 1, heightMax: 3,
    light: ["sun", "part-sun"],
    moisture: ["moist"],
    type: "perennial", native: true, pollinatorValue: true,
    color: ["purple", "blue"],
    difficulty: "easy",
    region: "west"
  },
  {
    id: 105,
    scientificName: "Dicentra formosa",
    commonName: "Pacific Bleeding Heart",
    heightMin: 1, heightMax: 2,
    light: ["shade", "part-shade"],
    moisture: ["moist"],
    type: "perennial", native: true, pollinatorValue: true,
    color: ["pink"],
    difficulty: "easy",
    region: "west",
    notes: "Western counterpart to Eastern bleeding heart. Blooms spring through summer, spreads by rhizome."
  },
  {
    id: 106,
    scientificName: "Sisyrinchium bellum",
    commonName: "Blue-eyed Grass",
    heightMin: 0.5, heightMax: 1.5,
    light: ["sun", "part-sun"],
    moisture: ["dry", "moist"],
    type: "perennial", native: true, pollinatorValue: true,
    color: ["blue", "violet"],
    difficulty: "easy",
    region: "west"
  },
  {
    id: 107,
    scientificName: "Camassia leichtlinii",
    commonName: "Camas",
    heightMin: 1, heightMax: 3,
    light: ["sun", "part-sun"],
    moisture: ["wet", "moist"],
    type: "bulb", native: true, pollinatorValue: true,
    color: ["blue", "purple"],
    difficulty: "easy",
    region: "west",
    notes: "Historically important food plant for many Pacific Northwest peoples. Stunning in mass plantings."
  },
  {
    id: 108,
    scientificName: "Sidalcea spp.",
    commonName: "Checker-Mallow",
    heightMin: 1, heightMax: 4,
    light: ["sun", "part-sun"],
    moisture: ["dry", "moist"],
    type: "perennial", native: true, pollinatorValue: true,
    color: ["pink"],
    difficulty: "moderate",
    region: "west"
  },
  {
    id: 109,
    scientificName: "Aquilegia formosa",
    commonName: "Western Red Columbine",
    heightMin: 1, heightMax: 3,
    light: ["sun", "part-shade"],
    moisture: ["moist"],
    type: "perennial", native: true, pollinatorValue: true,
    color: ["red", "yellow"],
    difficulty: "easy",
    region: "west",
    notes: "Hummingbird favorite. Western counterpart to Eastern Wild Columbine — same jewel-toned red and yellow."
  },
  {
    id: 110,
    scientificName: "Solidago spp.",
    commonName: "Goldenrod",
    heightMin: 2, heightMax: 5,
    light: ["sun", "part-sun"],
    moisture: ["dry", "moist"],
    type: "perennial", native: true, pollinatorValue: true,
    color: ["yellow"],
    difficulty: "easy",
    region: "west"
  },
  {
    id: 111,
    scientificName: "Iris douglasiana",
    commonName: "Douglas' Iris",
    heightMin: 0.5, heightMax: 1.5,
    light: ["sun", "part-shade"],
    moisture: ["dry", "moist"],
    type: "perennial", native: true, pollinatorValue: true,
    color: ["purple", "blue"],
    difficulty: "easy",
    region: "west"
  },
  {
    id: 112,
    scientificName: "Iris innominata",
    commonName: "Golden Iris",
    heightMin: 0.5, heightMax: 1,
    light: ["sun", "part-shade"],
    moisture: ["dry"],
    type: "perennial", native: true, pollinatorValue: true,
    color: ["yellow", "orange"],
    difficulty: "moderate",
    region: "west",
    notes: "Stunning but particular — needs excellent drainage and protection from wet winters."
  },
  {
    id: 113,
    scientificName: "Iris tenax",
    commonName: "Oregon Iris",
    heightMin: 0.5, heightMax: 1.5,
    light: ["sun", "part-sun"],
    moisture: ["dry", "moist"],
    type: "perennial", native: true, pollinatorValue: true,
    color: ["purple", "blue"],
    difficulty: "easy",
    region: "west"
  },
  {
    id: 114,
    scientificName: "Mimulus guttatus",
    commonName: "Yellow Monkeyflower",
    heightMin: 0.5, heightMax: 3,
    light: ["sun", "part-sun"],
    moisture: ["wet", "moist"],
    type: "perennial", native: true, pollinatorValue: true,
    color: ["yellow"],
    difficulty: "easy",
    region: "west"
  },
  {
    id: 115,
    scientificName: "Eriophyllum lanatum",
    commonName: "Oregon Sunshine",
    heightMin: 0.5, heightMax: 1.5,
    light: ["sun"],
    moisture: ["dry"],
    type: "perennial", native: true, pollinatorValue: true,
    color: ["yellow"],
    difficulty: "easy",
    region: "west",
    notes: "Tough, cheerful, drought-tolerant daisy. One of the easiest and most reliable west coast natives."
  },
  {
    id: 116,
    scientificName: "Anaphalis margaritacea",
    commonName: "Common Pearly Everlasting",
    heightMin: 1, heightMax: 2,
    light: ["sun", "part-sun"],
    moisture: ["dry", "moist"],
    type: "perennial", native: true, pollinatorValue: true,
    color: ["white"],
    difficulty: "easy",
    region: "west",
    notes: "Papery white blooms dry beautifully — excellent for dried arrangements. Spreads by rhizome."
  },
  {
    id: 117,
    scientificName: "Penstemon serrulatus",
    commonName: "Cascade Penstemon",
    heightMin: 1, heightMax: 2,
    light: ["sun", "part-sun"],
    moisture: ["moist"],
    type: "perennial", native: true, pollinatorValue: true,
    color: ["blue", "purple"],
    difficulty: "moderate",
    region: "west"
  },
  {
    id: 118,
    scientificName: "Sedum spathulifolium",
    commonName: "Broadleaf Stonecrop",
    heightMin: 0.2, heightMax: 0.5,
    light: ["sun"],
    moisture: ["dry"],
    type: "perennial", native: true, pollinatorValue: true,
    color: ["yellow"],
    difficulty: "easy",
    region: "west",
    notes: "Low succulent ground cover, only 2–6 inches. Thrives in rocky, poor soil where little else will grow."
  },
  {
    id: 119,
    scientificName: "Achillea millefolium",
    commonName: "Yarrow",
    heightMin: 1, heightMax: 3,
    light: ["sun"],
    moisture: ["dry", "moist"],
    type: "perennial", native: true, pollinatorValue: true,
    color: ["white", "pink", "yellow"],
    difficulty: "easy",
    region: "west",
    notes: "Extremely tough and adaptable. Also found across eastern North America — a true generalist wildflower."
  },

  // --- West Coast: Annuals ---
  {
    id: 120,
    scientificName: "Clarkia amoena",
    commonName: "Farewell-to-Spring",
    heightMin: 1, heightMax: 2.5,
    light: ["sun"],
    moisture: ["dry"],
    type: "annual", native: true, pollinatorValue: true,
    color: ["pink", "purple"],
    difficulty: "easy",
    region: "west",
    notes: "Direct sow in fall or early spring — does not transplant well. One of the showiest native annuals."
  },
  {
    id: 121,
    scientificName: "Gilia capitata",
    commonName: "Globe Gilia",
    heightMin: 1, heightMax: 2,
    light: ["sun"],
    moisture: ["dry"],
    type: "annual", native: true, pollinatorValue: true,
    color: ["blue", "purple"],
    difficulty: "easy",
    region: "west",
    notes: "Powder-puff blue blooms beloved by native bees. Direct sow in fall for best results."
  },
  {
    id: 122,
    scientificName: "Eschscholzia californica",
    commonName: "California Poppy",
    heightMin: 0.5, heightMax: 1.5,
    light: ["sun"],
    moisture: ["dry"],
    type: "annual", native: true, pollinatorValue: true,
    color: ["orange", "yellow"],
    difficulty: "easy",
    region: "west",
    notes: "State flower of California. Self-seeds prolifically — plant once and it returns every year."
  },

  // --- California Natives ---
  {
    id: 123,
    scientificName: "Salvia spathacea",
    commonName: "Hummingbird Sage",
    heightMin: 1, heightMax: 3,
    light: ["part-shade", "shade"],
    moisture: ["dry"],
    type: "perennial", native: true, pollinatorValue: true,
    color: ["red", "pink"],
    difficulty: "easy",
    region: "california",
    notes: "Spreads by runners to form a fragrant ground cover. Irresistible to hummingbirds."
  },
  {
    id: 124,
    scientificName: "Salvia clevelandii",
    commonName: "Cleveland Sage",
    heightMin: 3, heightMax: 5,
    light: ["sun"],
    moisture: ["dry"],
    type: "perennial", native: true, pollinatorValue: true,
    color: ["blue", "purple"],
    difficulty: "easy",
    region: "california",
    notes: "Intensely fragrant shrubby sage. Extremely drought tolerant once established."
  },
  {
    id: 125,
    scientificName: "Ceanothus spp.",
    commonName: "California Lilac",
    heightMin: 2, heightMax: 8,
    light: ["sun"],
    moisture: ["dry"],
    type: "perennial", native: true, pollinatorValue: true,
    color: ["blue", "white"],
    difficulty: "moderate",
    region: "california",
    notes: "Spectacular spring bloom, vital for native bees. Dislikes summer water once established — do not irrigate."
  },
  {
    id: 126,
    scientificName: "Penstemon heterophyllus",
    commonName: "Foothill Penstemon",
    heightMin: 1, heightMax: 2,
    light: ["sun"],
    moisture: ["dry"],
    type: "perennial", native: true, pollinatorValue: true,
    color: ["blue", "purple"],
    difficulty: "easy",
    region: "california"
  },
  {
    id: 127,
    scientificName: "Mimulus aurantiacus",
    commonName: "Sticky Monkeyflower",
    heightMin: 2, heightMax: 4,
    light: ["sun", "part-sun"],
    moisture: ["dry"],
    type: "perennial", native: true, pollinatorValue: true,
    color: ["orange", "yellow"],
    difficulty: "easy",
    region: "california",
    notes: "Long blooming season. Tolerates drought and poor soil. Excellent hummingbird plant."
  },
  {
    id: 128,
    scientificName: "Eriogonum fasciculatum",
    commonName: "California Buckwheat",
    heightMin: 1, heightMax: 3,
    light: ["sun"],
    moisture: ["dry"],
    type: "perennial", native: true, pollinatorValue: true,
    color: ["white", "pink"],
    difficulty: "easy",
    region: "california",
    notes: "One of the most important pollinator plants in California. Blooms age to rusty red — beautiful year-round."
  },
  {
    id: 129,
    scientificName: "Leymus condensatus",
    commonName: "Giant Wild Rye",
    heightMin: 4, heightMax: 8,
    light: ["sun", "part-shade"],
    moisture: ["dry"],
    type: "grass", native: true, pollinatorValue: false,
    color: ["foliage"],
    difficulty: "easy",
    region: "california",
    notes: "Bold architectural grass. Provides dramatic structure and important bird habitat."
  },
  {
    id: 130,
    scientificName: "Iris douglasiana",
    commonName: "Douglas Iris",
    heightMin: 0.5, heightMax: 1.5,
    light: ["sun", "part-shade"],
    moisture: ["dry", "moist"],
    type: "perennial", native: true, pollinatorValue: true,
    color: ["purple", "blue"],
    difficulty: "easy",
    region: "california"
  },
  {
    id: 131,
    scientificName: "Nassella pulchra",
    commonName: "Purple Needlegrass",
    heightMin: 1, heightMax: 3,
    light: ["sun"],
    moisture: ["dry"],
    type: "grass", native: true, pollinatorValue: false,
    color: ["foliage"],
    difficulty: "easy",
    region: "california",
    notes: "State grass of California. Deep roots make it extremely drought tolerant and great for erosion control."
  },
  {
    id: 132,
    scientificName: "Lupinus succulentus",
    commonName: "Arroyo Lupine",
    heightMin: 1, heightMax: 3,
    light: ["sun"],
    moisture: ["dry"],
    type: "annual", native: true, pollinatorValue: true,
    color: ["blue", "purple"],
    difficulty: "easy",
    region: "california",
    notes: "Fast-growing annual that fixes nitrogen. Direct sow in fall — puts on a spectacular spring show."
  },
  {
    id: 133,
    scientificName: "Achillea millefolium",
    commonName: "Yarrow",
    heightMin: 1, heightMax: 2,
    light: ["sun"],
    moisture: ["dry", "moist"],
    type: "perennial", native: true, pollinatorValue: true,
    color: ["white", "yellow"],
    difficulty: "easy",
    region: "california"
  },
  {
    id: 134,
    scientificName: "Romneya coulteri",
    commonName: "Matilija Poppy",
    heightMin: 4, heightMax: 8,
    light: ["sun"],
    moisture: ["dry"],
    type: "perennial", native: true, pollinatorValue: true,
    color: ["white", "yellow"],
    difficulty: "moderate",
    region: "california",
    notes: "Enormous fried-egg flowers are unforgettable. Spreads aggressively by underground runners — give it space."
  },
  {
    id: 135,
    scientificName: "Calystegia macrostegia",
    commonName: "Island Morning Glory",
    heightMin: 1, heightMax: 10,
    light: ["sun", "part-sun"],
    moisture: ["dry"],
    type: "perennial", native: true, pollinatorValue: true,
    color: ["white", "pink"],
    difficulty: "easy",
    region: "california",
    notes: "Fast-growing vine. Excellent for covering fences and trellises with minimal water."
  },

  // --- Pacific Northwest Shade & Woodland ---
  {
    id: 136,
    scientificName: "Trillium ovatum",
    commonName: "Pacific Trillium",
    heightMin: 0.5, heightMax: 1.5,
    light: ["shade", "part-shade"],
    moisture: ["moist"],
    type: "perennial", native: true, pollinatorValue: false,
    color: ["white"],
    difficulty: "challenging",
    region: "west",
    notes: "Icon of the Pacific Northwest woodland. Very slow growing — buy nursery propagated only, never wild-collected."
  },
  {
    id: 137,
    scientificName: "Oxalis oregana",
    commonName: "Oregon Wood Sorrel",
    heightMin: 0.25, heightMax: 0.5,
    light: ["shade"],
    moisture: ["moist"],
    type: "perennial", native: true, pollinatorValue: true,
    color: ["white", "pink"],
    difficulty: "easy",
    region: "west",
    notes: "Lush, clover-like ground cover for deep shade. Spreads reliably under conifers where little else grows."
  },
  {
    id: 138,
    scientificName: "Polystichum munitum",
    commonName: "Western Sword Fern",
    heightMin: 2, heightMax: 4,
    light: ["shade", "part-shade"],
    moisture: ["dry", "moist"],
    type: "fern", native: true, pollinatorValue: false,
    color: ["foliage"],
    difficulty: "easy",
    region: "west",
    notes: "The backbone of Pacific Northwest shade gardens. Evergreen, tough, and beautiful year-round."
  },
  {
    id: 139,
    scientificName: "Maianthemum dilatatum",
    commonName: "False Lily-of-the-Valley",
    heightMin: 0.25, heightMax: 0.75,
    light: ["shade"],
    moisture: ["moist"],
    type: "perennial", native: true, pollinatorValue: true,
    color: ["white"],
    difficulty: "easy",
    region: "west",
    notes: "Spreads to form a dense, weed-suppressing carpet in moist shade. Red berries in fall."
  },
  {
    id: 140,
    scientificName: "Aquilegia formosa",
    commonName: "Western Columbine",
    heightMin: 1, heightMax: 3,
    light: ["part-shade", "sun"],
    moisture: ["moist"],
    type: "perennial", native: true, pollinatorValue: true,
    color: ["red", "yellow"],
    difficulty: "easy",
    region: "west",
    notes: "Essential hummingbird plant. Self-seeds freely in woodland gardens."
  },
  {
    id: 141,
    scientificName: "Blechnum spicant",
    commonName: "Deer Fern",
    heightMin: 1, heightMax: 2,
    light: ["shade", "part-shade"],
    moisture: ["wet", "moist"],
    type: "fern", native: true, pollinatorValue: false,
    color: ["foliage"],
    difficulty: "easy",
    region: "west",
    notes: "Distinctive two-tiered fronds. Evergreen and reliable in moist shade — a Pacific Northwest classic."
  },
  {
    id: 142,
    scientificName: "Cornus canadensis",
    commonName: "Bunchberry",
    heightMin: 0.25, heightMax: 0.5,
    light: ["shade", "part-shade"],
    moisture: ["moist"],
    type: "perennial", native: true, pollinatorValue: true,
    color: ["white"],
    difficulty: "moderate",
    region: "west",
    notes: "Miniature dogwood relative. White flowers followed by bright red berries. Needs cool, acidic, moist soil."
  },
  {
    id: 143,
    scientificName: "Tiarella trifoliata",
    commonName: "Foamflower",
    heightMin: 0.5, heightMax: 1,
    light: ["shade", "part-shade"],
    moisture: ["moist"],
    type: "perennial", native: true, pollinatorValue: true,
    color: ["white"],
    difficulty: "easy",
    region: "west",
    notes: "Western counterpart to Eastern foamflower. Delicate white spires in spring shade."
  },
  {
    id: 144,
    scientificName: "Adiantum aleuticum",
    commonName: "Five-finger Fern",
    heightMin: 1, heightMax: 2,
    light: ["shade", "part-shade"],
    moisture: ["moist"],
    type: "fern", native: true, pollinatorValue: false,
    color: ["foliage"],
    difficulty: "moderate",
    region: "west",
    notes: "Elegant fan-shaped fronds, similar to eastern Maidenhair. Needs consistent moisture and humidity."
  },

  // --- Great Plains & Midwest Natives ---
  {
    id: 145,
    scientificName: "Ratibida columnifera",
    commonName: "Prairie Coneflower",
    heightMin: 1, heightMax: 3,
    light: ["sun"],
    moisture: ["dry", "moist"],
    type: "perennial", native: true, pollinatorValue: true,
    color: ["yellow", "red"],
    difficulty: "easy",
    region: "midwest",
    notes: "Distinctive thimble-shaped center cone. Extremely drought tolerant once established."
  },
  {
    id: 146,
    scientificName: "Echinacea pallida",
    commonName: "Pale Purple Coneflower",
    heightMin: 2, heightMax: 4,
    light: ["sun"],
    moisture: ["dry"],
    type: "perennial", native: true, pollinatorValue: true,
    color: ["pink", "purple"],
    difficulty: "easy",
    region: "midwest"
  },
  {
    id: 147,
    scientificName: "Echinacea purpurea",
    commonName: "Purple Coneflower",
    heightMin: 2, heightMax: 4,
    light: ["sun", "part-sun"],
    moisture: ["dry", "moist"],
    type: "perennial", native: true, pollinatorValue: true,
    color: ["purple", "pink"],
    difficulty: "easy",
    region: "midwest",
    notes: "One of the most beloved and versatile native plants. Seedheads feed goldfinches through winter."
  },
  {
    id: 148,
    scientificName: "Dalea purpurea",
    commonName: "Purple Prairie Clover",
    heightMin: 1, heightMax: 2,
    light: ["sun"],
    moisture: ["dry"],
    type: "perennial", native: true, pollinatorValue: true,
    color: ["purple", "pink"],
    difficulty: "easy",
    region: "midwest",
    notes: "Fixes nitrogen and thrives in poor, dry soil. Important for native bees."
  },
  {
    id: 149,
    scientificName: "Baptisia alba",
    commonName: "White Wild Indigo",
    heightMin: 3, heightMax: 5,
    light: ["sun", "part-sun"],
    moisture: ["dry", "moist"],
    type: "perennial", native: true, pollinatorValue: true,
    color: ["white"],
    difficulty: "moderate",
    region: "midwest",
    notes: "Long-lived prairie staple. Slow to establish but spectacular once settled — do not move after planting."
  },
  {
    id: 150,
    scientificName: "Bouteloua gracilis",
    commonName: "Blue Grama Grass",
    heightMin: 1, heightMax: 2,
    light: ["sun"],
    moisture: ["dry"],
    type: "grass", native: true, pollinatorValue: false,
    color: ["foliage"],
    difficulty: "easy",
    region: "midwest",
    notes: "Iconic prairie grass with distinctive comb-like seedheads. Extremely drought and cold tolerant."
  },
  {
    id: 151,
    scientificName: "Amorpha canescens",
    commonName: "Lead Plant",
    heightMin: 2, heightMax: 3,
    light: ["sun"],
    moisture: ["dry"],
    type: "perennial", native: true, pollinatorValue: true,
    color: ["purple", "blue"],
    difficulty: "easy",
    region: "midwest",
    notes: "Indicator species of high-quality prairie. Deep-rooted and extremely drought tolerant once established."
  },
  {
    id: 152,
    scientificName: "Dodecatheon meadia",
    commonName: "Shooting Star",
    heightMin: 0.5, heightMax: 1.5,
    light: ["sun", "part-shade"],
    moisture: ["moist"],
    type: "perennial", native: true, pollinatorValue: true,
    color: ["pink", "lavender"],
    difficulty: "moderate",
    region: "midwest",
    notes: "Distinctive swept-back petals like a shooting star. Spring ephemeral — goes dormant by summer."
  },
  {
    id: 153,
    scientificName: "Penstemon grandiflorus",
    commonName: "Large-flowered Beardtongue",
    heightMin: 2, heightMax: 3,
    light: ["sun"],
    moisture: ["dry"],
    type: "perennial", native: true, pollinatorValue: true,
    color: ["lavender", "pink"],
    difficulty: "easy",
    region: "midwest",
    notes: "One of the showiest native penstemons. Large tubular flowers in early summer."
  },
  {
    id: 154,
    scientificName: "Tradescantia ohiensis",
    commonName: "Ohio Spiderwort",
    heightMin: 1, heightMax: 3,
    light: ["sun", "part-sun"],
    moisture: ["dry", "moist"],
    type: "perennial", native: true, pollinatorValue: true,
    color: ["blue", "purple"],
    difficulty: "easy",
    region: "midwest"
  },
  {
    id: 155,
    scientificName: "Silphium laciniatum",
    commonName: "Compass Plant",
    heightMin: 4, heightMax: 9,
    light: ["sun"],
    moisture: ["dry", "moist"],
    type: "perennial", native: true, pollinatorValue: true,
    color: ["yellow"],
    difficulty: "easy",
    region: "midwest",
    notes: "Leaves orient north-south, historically used for navigation. Deep taproot — do not transplant once established."
  },
  {
    id: 156,
    scientificName: "Sporobolus heterolepis",
    commonName: "Prairie Dropseed",
    heightMin: 1, heightMax: 2,
    light: ["sun"],
    moisture: ["dry"],
    type: "grass", native: true, pollinatorValue: false,
    color: ["foliage"],
    difficulty: "easy",
    region: "midwest",
    notes: "Fragrant blooms and stunning fall color. One of the most beautiful native grasses."
  },
  {
    id: 157,
    scientificName: "Asclepias syriaca",
    commonName: "Common Milkweed",
    heightMin: 2, heightMax: 5,
    light: ["sun"],
    moisture: ["dry", "moist"],
    type: "perennial", native: true, pollinatorValue: true,
    color: ["pink", "lavender"],
    difficulty: "easy",
    region: "midwest",
    notes: "The most important monarch butterfly host plant in the midwest. Spreads by rhizome — give it room."
  },
  {
    id: 158,
    scientificName: "Gaillardia pulchella",
    commonName: "Indian Blanket",
    heightMin: 1, heightMax: 2,
    light: ["sun"],
    moisture: ["dry"],
    type: "annual", native: true, pollinatorValue: true,
    color: ["red", "yellow", "orange"],
    difficulty: "easy",
    region: "midwest",
    notes: "Vivid annual that self-seeds reliably. One of the longest-blooming native wildflowers."
  },

  // --- Southwest & Desert Natives ---
  {
    id: 159,
    scientificName: "Penstemon eatonii",
    commonName: "Firecracker Penstemon",
    heightMin: 1, heightMax: 3,
    light: ["sun"],
    moisture: ["dry"],
    type: "perennial", native: true, pollinatorValue: true,
    color: ["red"],
    difficulty: "easy",
    region: "southwest",
    notes: "Brilliant red tubes are a hummingbird magnet. One of the most reliable and showy desert penstemons."
  },
  {
    id: 160,
    scientificName: "Salvia farinacea",
    commonName: "Mealy Blue Sage",
    heightMin: 1, heightMax: 3,
    light: ["sun"],
    moisture: ["dry"],
    type: "perennial", native: true, pollinatorValue: true,
    color: ["blue", "purple"],
    difficulty: "easy",
    region: "southwest"
  },
  {
    id: 161,
    scientificName: "Agave parryi",
    commonName: "Parry's Agave",
    heightMin: 1, heightMax: 2,
    light: ["sun"],
    moisture: ["dry"],
    type: "perennial", native: true, pollinatorValue: true,
    color: ["yellow"],
    difficulty: "easy",
    region: "southwest",
    notes: "Architectural rosette of blue-grey leaves. Blooms once after many years then dies, leaving offsets."
  },
  {
    id: 162,
    scientificName: "Encelia farinosa",
    commonName: "Brittlebush",
    heightMin: 2, heightMax: 4,
    light: ["sun"],
    moisture: ["dry"],
    type: "perennial", native: true, pollinatorValue: true,
    color: ["yellow"],
    difficulty: "easy",
    region: "southwest",
    notes: "Iconic Sonoran Desert shrub with silver foliage and golden flowers. Drought and heat tolerant."
  },
  {
    id: 163,
    scientificName: "Sphaeralcea ambigua",
    commonName: "Desert Globemallow",
    heightMin: 1, heightMax: 3,
    light: ["sun"],
    moisture: ["dry"],
    type: "perennial", native: true, pollinatorValue: true,
    color: ["orange", "pink"],
    difficulty: "easy",
    region: "southwest",
    notes: "Brilliant orange blooms pop against silver-green foliage. Beloved by specialist globemallow bees."
  },
  {
    id: 164,
    scientificName: "Baileya multiradiata",
    commonName: "Desert Marigold",
    heightMin: 1, heightMax: 2,
    light: ["sun"],
    moisture: ["dry"],
    type: "perennial", native: true, pollinatorValue: true,
    color: ["yellow"],
    difficulty: "easy",
    region: "southwest",
    notes: "Blooms nearly year-round in warm climates. Silver woolly foliage reflects heat beautifully."
  },
  {
    id: 165,
    scientificName: "Penstemon pseudospectabilis",
    commonName: "Desert Beardtongue",
    heightMin: 2, heightMax: 4,
    light: ["sun"],
    moisture: ["dry"],
    type: "perennial", native: true, pollinatorValue: true,
    color: ["pink", "purple"],
    difficulty: "easy",
    region: "southwest"
  },
  {
    id: 166,
    scientificName: "Muhlenbergia rigens",
    commonName: "Deer Grass",
    heightMin: 2, heightMax: 4,
    light: ["sun", "part-sun"],
    moisture: ["dry", "moist"],
    type: "grass", native: true, pollinatorValue: false,
    color: ["foliage"],
    difficulty: "easy",
    region: "southwest",
    notes: "Graceful fountain-shaped grass. Extremely tough and adaptable — works in desert and coastal gardens."
  },
  {
    id: 167,
    scientificName: "Larrea tridentata",
    commonName: "Creosote Bush",
    heightMin: 3, heightMax: 8,
    light: ["sun"],
    moisture: ["dry"],
    type: "perennial", native: true, pollinatorValue: true,
    color: ["yellow"],
    difficulty: "easy",
    region: "southwest",
    notes: "The dominant shrub of the Mojave and Sonoran Deserts. The iconic desert scent after rain. Extremely long-lived."
  },
  {
    id: 168,
    scientificName: "Gaillardia pinnatifida",
    commonName: "Navajo Blanketflower",
    heightMin: 0.5, heightMax: 1.5,
    light: ["sun"],
    moisture: ["dry"],
    type: "perennial", native: true, pollinatorValue: true,
    color: ["red", "yellow", "orange"],
    difficulty: "easy",
    region: "southwest"
  },
  {
    id: 169,
    scientificName: "Callirhoe involucrata",
    commonName: "Purple Poppy Mallow",
    heightMin: 0.5, heightMax: 1,
    light: ["sun"],
    moisture: ["dry"],
    type: "perennial", native: true, pollinatorValue: true,
    color: ["purple", "pink"],
    difficulty: "easy",
    region: "southwest",
    notes: "Trailing ground cover with vivid magenta-purple blooms. Deep taproot makes it very drought tolerant."
  },
  {
    id: 170,
    scientificName: "Yucca baccata",
    commonName: "Banana Yucca",
    heightMin: 2, heightMax: 4,
    light: ["sun"],
    moisture: ["dry"],
    type: "perennial", native: true, pollinatorValue: true,
    color: ["white", "purple"],
    difficulty: "easy",
    region: "southwest",
    notes: "Dramatic architectural plant. Flowers are pollinated exclusively by yucca moths — a fascinating relationship."
  },

  // --- San Jose / Bay Area California Natives ---
  {
    id: 171,
    scientificName: "Arctostaphylos spp.",
    commonName: "Manzanita",
    heightMin: 1, heightMax: 15,
    light: ["sun"],
    moisture: ["dry"],
    type: "shrub", native: true, pollinatorValue: true,
    color: ["white", "pink"],
    difficulty: "moderate",
    region: "california",
    clayTolerance: "fair",
    bloomSeason: "Winter–Spring",
    notes: "Iconic California shrub with beautiful smooth red bark. Needs excellent drainage — does not tolerate wet roots. Huge variety of sizes available."
  },
  {
    id: 172,
    scientificName: "Heteromeles arbutifolia",
    commonName: "Toyon",
    heightMin: 8, heightMax: 15,
    light: ["sun", "part-shade"],
    moisture: ["dry", "moist"],
    type: "shrub", native: true, pollinatorValue: true,
    color: ["white"],
    difficulty: "easy",
    region: "california",
    clayTolerance: "excellent",
    bloomSeason: "Late Spring",
    notes: "Hollywood's namesake plant. White summer flowers followed by brilliant red winter berries — vital wildlife food source. Very clay tolerant."
  },
  {
    id: 173,
    scientificName: "Epilobium canum",
    commonName: "California Fuchsia",
    heightMin: 1, heightMax: 3,
    light: ["sun"],
    moisture: ["dry"],
    type: "perennial", native: true, pollinatorValue: true,
    color: ["red", "orange"],
    difficulty: "easy",
    region: "california",
    clayTolerance: "fair",
    bloomSeason: "Late Summer–Fall",
    notes: "Blazing red-orange blooms in late summer when most plants are done. Essential hummingbird plant for fall migration."
  },
  {
    id: 174,
    scientificName: "Monardella villosa",
    commonName: "Coyote Mint",
    heightMin: 1, heightMax: 2,
    light: ["sun", "part-shade"],
    moisture: ["dry"],
    type: "perennial", native: true, pollinatorValue: true,
    color: ["purple", "lavender"],
    difficulty: "easy",
    region: "california",
    clayTolerance: "fair",
    bloomSeason: "Summer",
    notes: "Intensely fragrant mint-family plant. Covered in butterflies and native bees when in bloom."
  },
  {
    id: 175,
    scientificName: "Cercis occidentalis",
    commonName: "Western Redbud",
    heightMin: 10, heightMax: 15,
    light: ["sun", "part-shade"],
    moisture: ["dry"],
    type: "tree", native: true, pollinatorValue: true,
    color: ["pink", "purple"],
    difficulty: "easy",
    region: "california",
    clayTolerance: "good",
    bloomSeason: "Early Spring",
    notes: "One of California's most spectacular native trees — magenta blooms coat bare branches before leaves emerge. Excellent clay tolerance."
  },

  // --- Oregon Shade Groundcovers & Woodland Plants ---
  {
    id: 176,
    scientificName: "Vancouveria hexandra",
    commonName: "Inside-out Flower",
    heightMin: 0.5, heightMax: 1,
    light: ["shade", "part-shade"],
    moisture: ["moist"],
    type: "perennial", native: true, pollinatorValue: true,
    color: ["white"],
    difficulty: "easy",
    region: "west",
    bloomSeason: "Spring",
    notes: "Delicate white flowers with swept-back petals — like tiny inside-out umbrellas. Spreads to form a lovely ground cover under conifers."
  },
  {
    id: 177,
    scientificName: "Fragaria vesca",
    commonName: "Woods Strawberry",
    heightMin: 0.25, heightMax: 0.5,
    light: ["part-shade", "part-sun"],
    moisture: ["dry", "moist"],
    type: "perennial", native: true, pollinatorValue: true,
    color: ["white"],
    difficulty: "easy",
    region: "west",
    bloomSeason: "Spring–Summer",
    notes: "Produces small, intensely flavored wild strawberries. Spreads by runners to form a charming edible ground cover."
  },
  {
    id: 178,
    scientificName: "Tellima grandiflora",
    commonName: "Fringecup",
    heightMin: 1, heightMax: 2,
    light: ["shade", "part-shade"],
    moisture: ["moist"],
    type: "perennial", native: true, pollinatorValue: true,
    color: ["white", "pink"],
    difficulty: "easy",
    region: "west",
    bloomSeason: "Spring",
    notes: "Tall wands of fringed cup-shaped flowers over handsome evergreen foliage. Self-seeds gently and naturalizes beautifully."
  },
  {
    id: 179,
    scientificName: "Viola glabella",
    commonName: "Stream Violet",
    heightMin: 0.25, heightMax: 0.75,
    light: ["shade", "part-shade"],
    moisture: ["wet", "moist"],
    type: "perennial", native: true, pollinatorValue: true,
    color: ["yellow"],
    difficulty: "easy",
    region: "west",
    bloomSeason: "Spring",
    notes: "Cheerful yellow violet for moist woodland spots and stream banks. Heart-shaped leaves stay attractive all season."
  }
];
